# Generated by Django 3.2.4 on 2021-08-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_sale_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
