# Generated by Django 3.2.4 on 2021-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Categories',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='shop.Category'),
        ),
    ]
