# Generated by Django 3.2.4 on 2021-08-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.images'),
        ),
    ]
