# Generated by Django 3.2.4 on 2021-08-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
