# Generated by Django 3.2.4 on 2021-08-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210824_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.CharField(default='', max_length=50),
        ),
    ]
